#!/bin/bash

VERSION_DSPACE="5.1"

sudo apt-get update
sudo apt-get install -y language-pack-en
sudo apt-get install -y software-properties-common python-software-properties

#Remove software not needed to make the resultant instalattion a bit smaller
sudo apt-get remove -y brasero wodim tomboy f-spot gimp ekiga evolution transmission-common rhythmbox totem totem-plugins totem-common totem-mozilla maven2 transmission-gtk thunderbird xchat gimp parole xfburn 
sudo apt-get install -y openjdk-7-jdk 
sudo apt-get install -y ant ant-optional tomcat7 postgresql tomcat7-admin maven mc

#copiar o arquivo do tomcat
sudo cp tomcat7 /etc/default/tomcat7

#copiar o arquivo do postgresql
sudo cp pg_hba.conf /etc/postgresql/*/main/pg_hba.conf

# Clean up any old installation
echo Removing /dspace
sudo rm -rf /dspace
sudo rm -rf /dspace/*

# Stop tomcat
echo Stopping tomcat
sudo service tomcat7 stop

# Restart postgresql
echo Restarting service postgresql
sudo service postgresql restart

# Create the postgres user and database
echo Initalise the database
echo  - Dropping old dspace database
sudo -u postgres dropdb dspace
echo  - Dropping old dspace Postgres users
sudo -u postgres dropuser dspace
echo  - Creating the dspace Postgres user
sudo -u postgres psql "-c CREATE USER dspace WITH PASSWORD 'dspace' CREATEDB;"
echo  - Creating the dspace database
createdb -U dspace dspace

# Download DSpace
echo Download DSpace source
echo  - Removing old copy of dspace-src
sudo rm -rf /dspace-src

echo  - Downloading new copy of DSpace
sudo wget "http://sourceforge.net/projects/dspace/files/DSpace%20Stable/$VERSION_DSPACE/dspace-$VERSION_DSPACE-src-release.tar.gz"
echo  - Extracting the DSpace to /dspace-src
sudo tar -vzxf "dspace-$VERSION_DSPACE-src-release.tar.gz"
# Remove unnecessary file
echo  - Removing file downloaded
sudo rm "dspace-$VERSION_DSPACE-src-release.tar.gz"

# Make the relevant directories
echo  - Making /dspace-src
sudo mkdir /dspace-src
sudo chown vagrant /dspace-src
sudo chown xubuntu /dspace-src

echo  - "Copying dspace-$VERSION_DSPACE-src-release to /dspace-src"
cp -R "dspace-$VERSION_DSPACE-src-release/"* /dspace-src
# Remove unnecessary folder
sudo rm -rf "dspace-$VERSION_DSPACE-src-release"

# Build DSpace-installed
echo Building DSpace
# Change build.properties
echo  - Copying build.properties to /dspace-src/build.properties
sudo cp -f build.properties /dspace-src/build.properties

echo  - Coping the customized dspace.cfg to /{dspace-build}/config
sudo cp -f dspace.cfg /dspace-src/dspace.cfg

echo Copying LiveCD ROOT webapp to dspace-src
sudo cp -f ROOT /dspace-src/ROOT

echo  - Running 'mvn package' on /dspace-src
cd /dspace-src/dspace/
sudo mvn -X package

echo  - Running ant fresh_install
cd "/dspace-src/dspace/target/dspace-installer/"
sudo ant fresh_install

# Create an admin user
echo Creating a DSpace admin user: username = dspace password = dspace
sudo /dspace/bin/dspace create-administrator -e dspace -f DSpace -l User -c en -p dspace

# Delete old tomcat webapps
echo Deleting old tomcat webapps
sudo rm -rf /var/lib/tomcat7/webapps/*

# Copy webapps to tomcat
echo Link webapps to tomcat
sudo ln -s /dspace/webapps/jspui /var/lib/tomcat7/webapps/jspui
sudo ln -s /dspace/webapps/oai /var/lib/tomcat7/webapps/oai
sudo ln -s /dspace/webapps/rdf /var/lib/tomcat7/webapps/rdf
sudo ln -s /dspace/webapps/rest /var/lib/tomcat7/webapps/rest
sudo ln -s /dspace/webapps/solr /var/lib/tomcat7/webapps/solr
sudo ln -s /dspace/webapps/sword /var/lib/tomcat7/webapps/sword
sudo ln -s /dspace/webapps/swordv2 /var/lib/tomcat7/webapps/swordv2
sudo ln -s /dspace/webapps/xmlui /var/lib/tomcat7/webapps/xmlui

echo Copying LiveCD ROOT webapp to tomcat
sudo cp -R /dspace-src/ROOT /var/lib/tomcat7/webapps/ROOT

# Start tomcat
echo Starting tomcat
sudo usermod -a -G vagrant tomcat7
sudo chown tomcat7:tomcat7 /dspace -R
sudo service tomcat7 start

# All done
echo
echo Build completed!
